website/urls.py
from django.urls import path, re_path

from . import views

app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("add_word/", views.add_word, name="add_word"),
    path("delete_word/<int:pk>/", views.delete_word, name="delete_word"),
]

words/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("website.urls"))
]

website/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Word(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    word = models.CharField(max_length=50)

    def __str__(self):
        return f"\"{self.word}\" belonging to {self.user.username}"

class Definition(models.Model):
    definition = models.TextField()
    word = models.ForeignKey(Word, on_delete=models.CASCADE, null=True)


class Example(models.Model):
    text = models.TextField()
    definition = models.ForeignKey(Definition, on_delete=models.CASCADE)

website/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import *

from . import my_utils as mu

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, "website/index.html")
    else:
        return HttpResponseRedirect(reverse('website:login'))


def login_user(request):
    context = {}
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("website:index"))
        else:
            context['errors'] = ["Your login credentials are invalid."]
    return render(request, "website/login.html", context=context)


def register_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]

        if User.objects.filter(username=username).exists():
            messages.add_message(request, messages.ERROR, "Username already exists!", fail_silently=True)
        elif password1 != password2:
            messages.add_message(request, messages.ERROR, "Passwords do not match", fail_silently=True)
        elif not mu.isPasswordSafe(password1):
            messages.error(request, "Password is not secure.")
        else:
            user = User.objects.create_user(username, email, password1, first_name=first_name, last_name=last_name)
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse("website:index"))

    return render(request, "website/register.html")


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse("website:index"))


def add_word(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return render(request, "website/add_word.html", context={})
        else:
            return HttpResponseRedirect(reverse("webite:index"))
    else:
        pass

def delete_word(request, pk):
    word = Word.objects.get(pk=pk)
    word.delete()
    return HttpResponseRedirect(reverse("website:index"))
    

website/templates/website/add_word.html
{% extends "website/layout.html" %}
{% block content %}
    <h1>Add Word</h1>
    <form action="{% url 'website:add_word' %}" method="POST">
        {% csrf_token %}

        <input type="text" placeholder="word" name="word">
        <input type="text" placeholder="definition" name="definition">
        <input type="text" placeholder="example" name="example">

        <input type="submit" value="submit">
    </form>
    <h2><a href="{% url 'website:index' %}">Back</a></h2>
{% endblock %}

website/templates/website/index.html
{% extends "website/layout.html" %}
{% block content %}
    <h1>Welcome to index!</h1>
    <ul>
        {% for word in user.word_set.all %}
            <li> 
                {{ word }}
                <form action="{% url 'website:delete_word' word.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="delete">
                </form>
            </li>
        {% endfor %}
    </ul>

    <h2><a href="{% url 'website:add_word' %}">Add Word</a></h2>
    <h2><a href="{% url 'website:logout' %}">Logout</a></h2>
{% endblock %}

website/templates/website/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
        
    {% endblock %}
</body>
</html>

website/templates/website/login.html
{% extends 'website/layout.html' %}

{% block content %}
    {% if errors %}
        <ul>
        {% for error in errors %}
            <li>{{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <h1>Login</h1>
    <form action="{% url 'website:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <input type="submit" value="Submit">
    </form>
    <a href="{% url 'website:register' %}">Register</a>
{% endblock %}

website/templates/website/register.html
{% extends "website/layout.html" %}
{% block content %}
    <h1>Signup</h1>

    {% if messages %}
        <ul>
            {% for message in messages %}        
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{% url "website:register" %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="email" name="email" placeholder="Email" required>
        <input type="password" name="password1" placeholder="Password" required>
        <input type="password" name="password2" placeholder="Confirm Password" required>
        <input type="text" name="first_name" placeholder="First Name">
        <input type="text" name="last_name" placeholder="Last Name">
        <br/>
        <input type="submit" value="Submit">
    </form>
    <a href="{% url 'website:login' %}">Login</a>
{% endblock %}